In [1]:
class CustomLinearRegression:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, X, y):
        num = 0
        den = 0
        print(X.shape[0])
        for i in range(X.shape[0]):
            num = num + (X[i] - X.mean()) * (y[i] - y.mean())
            den = den + (X[i] - X.mean()) ** 2

        self.m = num / den
        self.b = y.mean() - self.m * X.mean()

        print(f'm: {self.m}, b: {self.b}')

    def predict(self, X):
        return self.m * X + self.b

    def score(self, X, y):
        y_pred = self.predict(X)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - y.mean()) ** 2)
        r2_score = 1 - (ss_res / ss_tot)
        return r2_score


In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../../datasets/placement_SLR.csv')

In [4]:
X = df.iloc[:,:1]
y = df.iloc[:,1:2]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
X_train.values

array([[7.14],
       [8.93],
       [5.42],
       [5.1 ],
       [7.77],
       [6.76],
       [6.89],
       [6.68],
       [7.91],
       [7.89],
       [8.71],
       [7.95],
       [6.61],
       [6.26],
       [6.53],
       [6.42],
       [5.11],
       [6.09],
       [6.93],
       [7.04],
       [5.94],
       [6.05],
       [5.83],
       [5.95],
       [9.31],
       [5.58],
       [7.88],
       [6.13],
       [7.76],
       [4.85],
       [6.19],
       [8.6 ],
       [6.07],
       [7.18],
       [5.12],
       [7.39],
       [8.25],
       [8.28],
       [7.13],
       [7.35],
       [5.66],
       [5.99],
       [8.01],
       [7.14],
       [6.34],
       [6.89],
       [5.42],
       [6.47],
       [7.69],
       [7.4 ],
       [7.28],
       [5.95],
       [7.38],
       [6.93],
       [8.99],
       [7.36],
       [7.08],
       [5.38],
       [7.56],
       [8.22],
       [5.84],
       [6.78],
       [7.19],
       [7.28],
       [6.79],
       [6.12],
       [6.

In [12]:
X_test

,cgpa
112,8.58
29,7.15
182,5.88
199,6.22
193,4.57
85,4.79
10,5.32
54,6.86
115,8.35
35,6.87


In [13]:
y_test

,package
112,4.10
29,3.49
182,2.08
199,2.33
193,1.94
85,1.48
10,1.86
54,3.09
115,4.21
35,2.87


In [9]:
model = CustomLinearRegression()
model.fit(X_train.values, y_train.values)

160
m: [0.55795197], b: [-0.89611192]


In [15]:
model.predict(X_test.iloc[1].values.reshape(-1,1))

array([[3.09324469]])

In [16]:
model.predict(X_test.iloc[4].values.reshape(-1,1))

array([[1.6537286]])

In [17]:
model.score(X_test.values, y_test.values)

0.7807301475103842